version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: dnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/dnmp/www/:/var/www/html/:rw
      - ~/dnmp/conf/conf.d:/etc/nginx/conf.d/:ro
      - ~/dnmp/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/dnmp/log/:/var/log/dnmp/:rw
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
    links:
      - php
    networks:
      - net-php

  php:
    image: e8543420/php72:latest
    container_name: dnmp-php
    expose:
      - "9000"
    deploy:
      replicas: 5
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - ~/dnmp/www/:/var/www/html/:rw
      - ~/dnmp/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ~/dnmp/conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ~/dnmp/log/:/var/log/dnmp/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:latest
    container_name: dnmp-mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/dnmp/conf/my.cnf:/etc/mysql/my.cnf:ro
      - ~/dnmp/mysql/:/var/lib/mysql/:rw
      - ~/dnmp/log/:/var/log/dnmp/:rw
    networks:
      - net-mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - net-php
      - net-mysql
      - net-redis
      
  redis:
    image: redis:latest
    container_name: dnmp-redis
    networks:
      - net-redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes

networks:
  net-php:
  net-mysql:
  net-redis: